# docker-compose.yml

services:
  dockerhelper-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env         # Loads all variables from file
    # environment:
    #   - NODE_ENV=production
    #   - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000/api/v1}
    #   - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    #   - NEXT_PUBLIC_OAUTH_CALLBACK_URL=${NEXT_PUBLIC_OAUTH_CALLBACK_URL:-http://localhost:3000/oauth-callback}
    #   - NEXT_PUBLIC_ENABLE_GITHUB_LOGIN=${NEXT_PUBLIC_ENABLE_GITHUB_LOGIN:-true}
    #   - NEXT_PUBLIC_ENABLE_GOOGLE_LOGIN=${NEXT_PUBLIC_ENABLE_GOOGLE_LOGIN:-true}
    #   - NEXT_PUBLIC_ENABLE_GITLAB_LOGIN=${NEXT_PUBLIC_ENABLE_GITLAB_LOGIN:-true}
    #   - NEXT_PUBLIC_AUTH_ENABLED=${NEXT_PUBLIC_AUTH_ENABLED:-true}
    #   - NEXT_PUBLIC_PRODUCTION_URL=${NEXT_PUBLIC_PRODUCTION_URL:-http://localhost:3000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dockerhelper-network

networks:
  dockerhelper-network:
    driver: bridge
