# docker-compose.dev.yml

services:
  dockerhelper-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env         # Loads all variables from file
    # environment:
    #   - NODE_ENV=development
    #   - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    #   - NEXT_PUBLIC_APP_URL=http://localhost:3000
    #   - NEXT_PUBLIC_OAUTH_CALLBACK_URL=http://localhost:3000/oauth-callback
    #   - NEXT_PUBLIC_ENABLE_GITHUB_LOGIN=true
    #   - NEXT_PUBLIC_ENABLE_GOOGLE_LOGIN=true
    #   - NEXT_PUBLIC_ENABLE_GITLAB_LOGIN=true
    #   - NEXT_PUBLIC_AUTH_ENABLED=true
    #   - NEXT_PUBLIC_PRODUCTION_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - dockerhelper-network

networks:
  dockerhelper-network:
    driver: bridge
