# docker-compose.yaml

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL
        - NEXT_PUBLIC_AUTH_ENABLED
        - NEXT_PUBLIC_APP_URL
        - NEXT_PUBLIC_OAUTH_CALLBACK_URL
        - NEXT_PUBLIC_PRODUCTION_URL
        - NEXT_PUBLIC_ENABLE_GITHUB_LOGIN
        - NEXT_PUBLIC_ENABLE_GOOGLE_LOGIN
        - NEXT_PUBLIC_ANALYTICS_ID
    env_file:
      - .env.bunnyshell
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dockerhelper-network

networks:
  dockerhelper-network:
    driver: bridge