import type React from "react"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"
import {
  Cpu,
  Code,
  Layers,
  Zap,
  CheckCircle,
  ArrowRight,
  Github,
  Database,
  Server,
  RefreshCw,
  Rocket,
  FileCode2,
  Boxes,
} from "lucide-react"

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative overflow-hidden py-20 md:py-32 bg-gradient-to-br from-background via-background to-accent/5">
          <div className="absolute inset-0 bg-grid-pattern opacity-[0.03] dark:opacity-[0.05]"></div>
          <div className="container mx-auto px-4 relative z-10">
            <div className="flex flex-col md:flex-row items-center gap-12">
              <div className="flex-1 space-y-6 animate-in" style={{ "--index": 1 } as React.CSSProperties}>
                <Badge
                  variant="outline"
                  className="px-3 py-1 text-sm bg-accent/10 border-accent/20 text-accent-foreground animate-pulse"
                >
                  AI-Powered Docker Configuration
                </Badge>
                <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight">
                  <span className="block">Containerize Your Code</span>
                  <span className="block mt-2 text-transparent bg-clip-text bg-gradient-to-r from-primary to-accent">
                    Without the Hassle
                  </span>
                </h1>
                <p className="text-lg md:text-xl text-muted-foreground max-w-xl">
                  DockerHelper uses AI to analyze your repositories and automatically generate optimized Docker
                  configurations tailored to your project.
                </p>
                <div className="flex flex-wrap gap-4 pt-4">
                  <Link href="/register">
                    <Button size="lg" className="group hover:scale-105 transition-all duration-200">
                      Get Started
                      <ArrowRight className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
                    </Button>
                  </Link>
                  <Link href="/login">
                    <Button size="lg" variant="outline" className="hover:scale-105 transition-all duration-200">
                      Sign In
                    </Button>
                  </Link>
                </div>
              </div>
              <div className="flex-1 relative animate-in" style={{ "--index": 2 } as React.CSSProperties}>
                <div className="relative bg-background rounded-lg border shadow-xl p-1 hover:shadow-2xl transition-all duration-500 hover:scale-[1.02] hover:border-primary/50">
                  <div className="absolute -top-3 -right-3">
                    <Badge className="bg-accent text-accent-foreground">AI Generated</Badge>
                  </div>
                  <pre className="p-4 rounded-md bg-muted/50 overflow-hidden text-xs md:text-sm">
                    <code className="language-dockerfile">
                      <div className="text-green-500 dark:text-green-400"># Generated by DockerHelper AI</div>
                      <div className="text-blue-500 dark:text-blue-400">FROM node:18-alpine</div>
                      <br />
                      <div>WORKDIR /app</div>
                      <br />
                      <div>COPY package*.json ./</div>
                      <div className="text-purple-500 dark:text-purple-400">RUN npm install</div>
                      <br />
                      <div>COPY . .</div>
                      <br />
                      <div className="text-yellow-500 dark:text-yellow-400">EXPOSE 3000</div>
                      <br />
                      <div className="text-red-500 dark:text-red-400">CMD [&quot;npm&quot;, &quot;start&quot;]</div>
                    </code>
                  </pre>
                </div>
                <div className="absolute -z-10 -bottom-6 -right-6 w-64 h-64 bg-accent/20 rounded-full blur-3xl"></div>
                <div className="absolute -z-10 -top-6 -left-6 w-64 h-64 bg-primary/20 rounded-full blur-3xl"></div>
              </div>
            </div>
          </div>
        </section>

        {/* How It Works */}
        <section className="py-20 bg-muted/30">
          <div className="container mx-auto px-4">
            <div className="text-center mb-16 animate-in" style={{ "--index": 1 } as React.CSSProperties}>
              <Badge variant="outline" className="mb-4">
                The Process
              </Badge>
              <h2 className="text-3xl md:text-4xl font-bold mb-4">How DockerHelper Works</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Our AI-powered platform analyzes your code and generates optimized Docker configurations in just a few
                steps.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {[
                {
                  icon: <Github className="h-10 w-10 text-primary" />,
                  title: "Connect Repository",
                  description: "Link your GitHub repository or provide a Git URL to get started.",
                  delay: 2,
                },
                {
                  icon: <Cpu className="h-10 w-10 text-accent" />,
                  title: "AI Analysis",
                  description: "Our AI analyzes your code, dependencies, and structure to understand your project.",
                  delay: 3,
                },
                {
                  icon: <FileCode2 className="h-10 w-10 text-success" />,
                  title: "Generate Configuration",
                  description: "Receive optimized Dockerfile and docker-compose.yaml files tailored to your project.",
                  delay: 4,
                },
              ].map((item, index) => (
                <Card
                  key={index}
                  className="border-2 hover:border-primary/50 transition-all duration-300 hover:shadow-lg animate-in"
                  style={{ "--index": item.delay } as React.CSSProperties}
                >
                  <CardContent className="p-6 flex flex-col items-center text-center">
                    <div className="mb-4 p-3 rounded-full bg-muted">{item.icon}</div>
                    <h3 className="text-xl font-bold mb-2">{item.title}</h3>
                    <p className="text-muted-foreground">{item.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* Key Features */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <div className="text-center mb-16 animate-in" style={{ "--index": 1 } as React.CSSProperties}>
              <Badge variant="outline" className="mb-4">
                Features
              </Badge>
              <h2 className="text-3xl md:text-4xl font-bold mb-4">Why Choose DockerHelper</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Our platform offers powerful features to make containerization simple and efficient.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {[
                {
                  icon: <Zap className="h-6 w-6 text-warning" />,
                  title: "Instant Generation",
                  description: "Get Docker configurations in seconds, not hours.",
                },
                {
                  icon: <Layers className="h-6 w-6 text-primary" />,
                  title: "Multi-Service Support",
                  description: "Generate docker-compose files for complex applications.",
                },
                {
                  icon: <Code className="h-6 w-6 text-accent" />,
                  title: "Framework Detection",
                  description: "Automatically detects frameworks and languages.",
                },
                {
                  icon: <Database className="h-6 w-6 text-info" />,
                  title: "Database Integration",
                  description: "Includes database services in your compose files.",
                },
                {
                  icon: <RefreshCw className="h-6 w-6 text-success" />,
                  title: "Continuous Improvement",
                  description: "Configurations get better with your feedback.",
                },
                {
                  icon: <Server className="h-6 w-6 text-destructive" />,
                  title: "Version History",
                  description: "Track and revert to previous configurations.",
                },
              ].map((feature, index) => (
                <div
                  key={index}
                  className="flex items-start gap-4 p-4 rounded-lg hover:bg-muted/50 transition-colors duration-200 animate-in"
                  style={{ "--index": index + 2 } as React.CSSProperties}
                >
                  <div className="mt-1 p-2 rounded-full bg-background border">{feature.icon}</div>
                  <div>
                    <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                    <p className="text-muted-foreground">{feature.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Try It Now */}
        <section className="py-20 bg-gradient-to-br from-primary/5 via-background to-accent/5">
          <div className="container mx-auto px-4">
            <div
              className="bg-card rounded-xl shadow-lg border p-8 md:p-12 max-w-4xl mx-auto animate-in"
              style={{ "--index": 1 } as React.CSSProperties}
            >
              <div className="flex flex-col md:flex-row gap-8 items-center">
                <div className="flex-1">
                  <h2 className="text-3xl font-bold mb-4">Ready to Simplify Your Docker Workflow?</h2>
                  <p className="text-muted-foreground mb-6">
                    Join thousands of developers who are saving time with AI-generated Docker configurations.
                  </p>
                  <div className="flex flex-wrap gap-4">
                    <Link href="/register">
                      <Button size="lg" className="group">
                        Try It Free
                        <Rocket className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
                      </Button>
                    </Link>
                    <Link href="#features">
                      <Button size="lg" variant="outline">
                        Learn More
                      </Button>
                    </Link>
                  </div>
                </div>
                <div className="flex-shrink-0">
                  <div className="relative w-32 h-32 md:w-40 md:h-40">
                    <div className="absolute inset-0 rounded-full bg-primary/20 animate-pulse"></div>
                    <div className="absolute inset-4 rounded-full bg-primary/30 animate-pulse [animation-delay:300ms]"></div>
                    <div className="absolute inset-8 rounded-full bg-primary/40 animate-pulse [animation-delay:600ms]"></div>
                    <div className="absolute inset-0 flex items-center justify-center">
                      <Boxes className="h-12 w-12 text-primary" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Testimonials */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <div className="text-center mb-16 animate-in" style={{ "--index": 1 } as React.CSSProperties}>
              <Badge variant="outline" className="mb-4">
                Testimonials
              </Badge>
              <h2 className="text-3xl md:text-4xl font-bold mb-4">What Developers Say</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Join the community of developers who have simplified their Docker workflow.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {[
                {
                  quote:
                    "DockerHelper saved me hours of configuration work. The generated Dockerfiles work perfectly for my Node.js projects.",
                  author: "Sarah K.",
                  role: "Full Stack Developer",
                },
                {
                  quote:
                    "I was struggling with docker-compose for my microservices. This tool made it incredibly simple to set up.",
                  author: "Michael T.",
                  role: "DevOps Engineer",
                },
                {
                  quote:
                    "As someone new to Docker, this tool has been a lifesaver. It helped me learn while providing working configurations.",
                  author: "Jamie L.",
                  role: "Junior Developer",
                },
              ].map((testimonial, index) => (
                <Card
                  key={index}
                  className="hover:shadow-lg transition-all duration-300 animate-in"
                  style={{ "--index": index + 2 } as React.CSSProperties}
                >
                  <CardContent className="p-6">
                    <div className="mb-4 text-4xl text-primary">&quot;</div>
                    <p className="mb-6 italic text-card-foreground">{testimonial.quote}</p>
                    <div className="flex items-center gap-2">
                      <div className="w-10 h-10 rounded-full bg-muted flex items-center justify-center">
                        <span className="font-semibold text-primary">{testimonial.author[0]}</span>
                      </div>
                      <div>
                        <p className="font-semibold">{testimonial.author}</p>
                        <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-20 bg-accent/10">
          <div
            className="container mx-auto px-4 text-center animate-in"
            style={{ "--index": 1 } as React.CSSProperties}
          >
            <h2 className="text-3xl md:text-4xl font-bold mb-6">Start Containerizing Your Applications Today</h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-8">
              Join thousands of developers who are using DockerHelper to simplify their Docker workflow.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Link href="/register">
                <Button size="lg" className="hover:scale-105 transition-all duration-200">
                  Create Free Account
                </Button>
              </Link>
              <Link href="/login">
                <Button size="lg" variant="outline" className="hover:scale-105 transition-all duration-200">
                  Sign In
                </Button>
              </Link>
            </div>
            <div className="mt-8 flex justify-center gap-4">
              {[
                <CheckCircle key="1" className="h-5 w-5 text-success" />,
                <CheckCircle key="2" className="h-5 w-5 text-success" />,
                <CheckCircle key="3" className="h-5 w-5 text-success" />,
              ].map((icon, index) => (
                <div key={index} className="flex items-center gap-2">
                  {icon}
                  <span className="text-sm">
                    {index === 0 ? "No credit card required" : index === 1 ? "Free tier available" : "Instant setup"}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
